### ISSUE TITLE
Enhancement: Column Adjustment Feature / Journal in third column

### ISSUE THREAD

**Issue by brandonm4** [nboughton/iron-journal#3]
Hello,
Would it be feasible to make the Journal section be able to appear as it's own column to the right of the moves/oracles?
I think it would be easier to manage instead of needing to scroll up to the moves/oracles and then back down to the journal.
I also have a fairly wide screen and it would be handy if the column widths could be stretched/shrunk by the user.

**Comment by nboughton** [comment]
Added toggle in left menu drawer to move journal into its own tab
